test:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p normal -t 0:05:00"
  script:
    - export FINN_SINGULARITY=$PC2DATA/hpc-prf-ekiapp/FINN_IMAGES/xilinx/finn_dev.sif
    - ./run-docker.sh quicktest
