Quicktest Singularity Image:
  stage: test
  variables:
    SCHEDULER_PARAMETERS: "-A $PROJECT_ACCOUNT -p normal -t 1:00:00"
    FINN_SINGULARITY: "$PATH_SINGULARITY_IMG/xilinx/finn_dev.sif"
  script:
    - module load system singularity
    - ./run-docker.sh quicktest
